"""Demo storefront configs for the deck gallery (slide 9). Not real businesses."""

U = "https://images.unsplash.com/photo-{}?w=800&q=70&auto=format&fit=crop"
RAW = {
    "coffee": {
        "kind": "menu",
        "title": "Кофейня у Чкаловской",
        "tagline": "Эспрессо, выпечка и десерты в двух минутах от метро",
        "about": "Готовим кофе на зерне средней обжарки и печём круассаны каждое утро. Заберите заказ по пути или посидите у окна.",
        "accent": "#B4532A",
        "mood": "warm",
        "layout": "cards",
        "color_scheme": "light",
        "heading_style": "serif",
        "design_concept": "Утренняя пекарня",
        "nav_style": "pills",
        "hero_style": "fullbleed",
        "card_style": "image-top",
        "radius_style": "soft",
        "density": "balanced",
        "contacts": {"address": "Чкаловский пр., 15", "hours": "ежедневно 8:00–22:00", "phone": ""},
        "items": [
            {
                "title": "Капучино",
                "description": "Двойной эспрессо и молоко",
                "price_rub": 290,
                "category": "Кофе",
                "image_url": U.format("1572442388796-11668a67e53d"),
                "badge": "хит",
            },
            {
                "title": "Флэт уайт",
                "description": "",
                "price_rub": 320,
                "category": "Кофе",
                "image_url": U.format("1577968897966-3d4325b36b61"),
            },
            {
                "title": "Раф лавандовый",
                "description": "Сливки, лаванда, ваниль",
                "price_rub": 360,
                "category": "Кофе",
                "image_url": U.format("1461023058943-07fcbe16d735"),
            },
            {
                "title": "Круассан с миндалём",
                "description": "",
                "price_rub": 240,
                "category": "Выпечка",
                "image_url": U.format("1555507036-ab1f4038808a"),
            },
            {
                "title": "Синнабон",
                "description": "",
                "price_rub": 260,
                "category": "Выпечка",
                "image_url": U.format("1509365465985-25d11c17e812"),
            },
            {
                "title": "Чизкейк Нью-Йорк",
                "description": "",
                "price_rub": 380,
                "category": "Десерты",
                "image_url": U.format("1533134242443-d4fd215305ad"),
            },
        ],
    },
    "tutor": {
        "kind": "booking",
        "title": "Анна Смирнова",
        "tagline": "Математика ЕГЭ и ОГЭ — спокойно и по плану",
        "about": "Готовлю к профильной математике с 8 класса. Занятия онлайн или у метро Петроградская, после каждого — домашнее задание и разбор.",
        "accent": "#1F4D3A",
        "mood": "calm",
        "layout": "editorial",
        "color_scheme": "light",
        "heading_style": "serif",
        "design_concept": "Тетрадь в клетку",
        "nav_style": "none",
        "hero_style": "typographic",
        "card_style": "minimal",
        "radius_style": "sharp",
        "density": "airy",
        "items": [
            {
                "title": "Пробное занятие",
                "description": "Определим уровень и составим план",
                "price_rub": 0,
                "duration_min": 45,
            },
            {
                "title": "Подготовка к ЕГЭ, профиль",
                "description": "",
                "price_rub": 2500,
                "duration_min": 90,
            },
            {"title": "Подготовка к ОГЭ", "description": "", "price_rub": 1800, "duration_min": 60},
        ],
        "slots": ["Чт 25 сен, 16:00", "Чт 25 сен, 18:00", "Пт 26 сен, 17:00", "Сб 27 сен, 11:00"],
        "comment_hint": "Класс, тема, онлайн или очно",
    },
    "barber": {
        "kind": "booking",
        "title": "BLADE",
        "tagline": "Барбершоп на Лиговском. Стрижка за 45 минут",
        "about": "Мужские стрижки, бороды и камуфляж седины. Кофе и плейстейшн, пока ждёте.",
        "accent": "#E4B343",
        "mood": "bold",
        "layout": "poster",
        "color_scheme": "dark",
        "heading_style": "display",
        "design_concept": "Неон и сталь",
        "nav_style": "tabs",
        "hero_style": "typographic",
        "card_style": "horizontal",
        "radius_style": "sharp",
        "density": "compact",
        "contacts": {"address": "Лиговский пр., 50", "hours": "10:00–22:00"},
        "items": [
            {
                "title": "Мужская стрижка",
                "price_rub": 1800,
                "duration_min": 45,
                "category": "Стрижки",
            },
            {
                "title": "Стрижка машинкой",
                "price_rub": 1200,
                "duration_min": 30,
                "category": "Стрижки",
            },
            {
                "title": "Моделирование бороды",
                "price_rub": 1200,
                "duration_min": 30,
                "category": "Борода",
            },
            {
                "title": "Королевское бритьё",
                "price_rub": 1600,
                "duration_min": 40,
                "category": "Борода",
            },
            {
                "title": "Отец + сын",
                "price_rub": 2900,
                "duration_min": 75,
                "category": "Комплексы",
                "badge": "выгодно",
            },
        ],
        "slots": ["Чт 25 сен, 12:00", "Чт 25 сен, 14:30", "Пт 26 сен, 19:00", "Сб 27 сен, 10:00"],
    },
    "nails": {
        "kind": "booking",
        "title": "Ноготочки на Васильевском",
        "tagline": "Маникюр и педикюр с покрытием, которое держится три недели",
        "about": "Работаем со стерильными инструментами из крафт-пакета. Два мастера, окна каждый день.",
        "accent": "#D9577E",
        "mood": "warm",
        "layout": "cards",
        "color_scheme": "light",
        "heading_style": "sans",
        "design_concept": "Розовый сорбет",
        "nav_style": "pills",
        "hero_style": "split",
        "card_style": "minimal",
        "radius_style": "round",
        "density": "balanced",
        "items": [
            {
                "title": "Маникюр с покрытием",
                "price_rub": 2200,
                "duration_min": 90,
                "category": "Руки",
            },
            {
                "title": "Снятие + маникюр",
                "price_rub": 1500,
                "duration_min": 60,
                "category": "Руки",
            },
            {
                "title": "Педикюр с покрытием",
                "price_rub": 2800,
                "duration_min": 90,
                "category": "Ноги",
            },
            {"title": "Дизайн, 1 ноготь", "price_rub": 150, "category": "Дизайн"},
        ],
        "slots": ["Чт 25 сен, 11:00", "Пт 26 сен, 15:00", "Сб 27 сен, 13:00"],
    },
    "lawyer": {
        "kind": "landing",
        "title": "Юрист по банкротству",
        "tagline": "Списание долгов физлиц через суд и МФЦ",
        "about": "Разбираем ситуацию на бесплатной консультации и говорим честно, подходит ли вам процедура.",
        "accent": "#2B3A67",
        "mood": "minimal",
        "layout": "classic",
        "color_scheme": "light",
        "heading_style": "sans",
        "design_concept": "Строгий документ",
        "nav_style": "none",
        "hero_style": "split",
        "card_style": "minimal",
        "radius_style": "soft",
        "density": "balanced",
        "items": [
            {"title": "Бесплатная консультация", "description": "30 минут по телефону или в офисе"}
        ],
    },
}
RAW["coffee"].update(
    {
        "heading_font": "cormorant",
        "hero_style": "fullbleed",
        "card_style": "image-top",
        "nav_style": "pills",
        "palette": {"bg": "#F4ECE1", "surface": "#FFF9F1", "ink": "#2A1A12", "accent2": "#7A2E14"},
        "pattern": "grain",
        "kicker": "Кофейня · с 8 утра",
        "catalog_title": "Что заказать",
        "marquee": True,
        "highlights": [
            {"value": "2 мин", "label": "от метро"},
            {"value": "8:00", "label": "открываемся"},
        ],
    }
)
RAW["tutor"].update(
    {
        "heading_font": "lora",
        "hero_style": "editorial",
        "card_style": "numbered",
        "hero_tone": "plain",
        "palette": {"bg": "#F5F3EC", "surface": "#FFFFFF", "ink": "#16231C", "accent2": "#8FB39A"},
        "pattern": "grid",
        "kicker": "Репетитор по математике",
        "catalog_title": "Форматы занятий",
        "highlights": [
            {"value": "8–11", "label": "классы"},
            {"value": "90 мин", "label": "занятие ЕГЭ"},
            {"value": "онлайн", "label": "или очно"},
        ],
    }
)
RAW["barber"].update(
    {
        "heading_font": "oswald",
        "hero_style": "typographic",
        "card_style": "menu",
        "hero_tone": "accent",
        "pattern": "stripes",
        "palette": {"bg": "#0E0E0F", "surface": "#18181A", "ink": "#F2EFE8", "accent2": "#C98B1C"},
        "kicker": "Барбершоп · Лиговский, 50",
        "catalog_title": "Прайс",
        "marquee": True,
        "highlights": [
            {"value": "45", "label": "минут стрижка"},
            {"value": "10–22", "label": "каждый день"},
        ],
    }
)
RAW["nails"].update(
    {
        "heading_font": "comfortaa",
        "hero_style": "split",
        "card_style": "overlay",
        "hero_tone": "accent",
        "pattern": "glow",
        "palette": {"bg": "#FFF1F4", "surface": "#FFFFFF", "ink": "#3A1622", "accent2": "#F29BB2"},
        "accent": "#C2345F",
        "kicker": "Маникюр · Васильевский",
        "catalog_title": "Выберите процедуру",
        "highlights": [
            {"value": "3 недели", "label": "держится покрытие"},
            {"value": "2", "label": "мастера"},
        ],
    }
)
RAW["lawyer"].update(
    {
        "heading_font": "playfair",
        "hero_style": "typographic",
        "card_style": "minimal",
        "hero_tone": "ink",
        "pattern": "rings",
        "palette": {"bg": "#F3F1EC", "surface": "#FFFFFF", "ink": "#141B2D", "accent2": "#B89B5E"},
        "accent": "#B89B5E",
        "kicker": "Банкротство физлиц",
        "catalog_title": "С чего начать",
        "highlights": [
            {"value": "0 ₽", "label": "первая консультация"},
            {"value": "30 мин", "label": "разбор ситуации"},
        ],
    }
)
