export const tokens = {
  color: {
    white: "var(--ar-white)",
    cloud: "var(--ar-cloud)",
    canvas: "var(--ar-canvas)",
    mist: "var(--ar-mist)",
    stone: "var(--ar-stone)",
    graphite: "var(--ar-graphite)",
    black: "var(--ar-black)",
    sky: "var(--ar-sky)",
    cyan: "var(--ar-cyan)",
    indigo: "var(--ar-indigo)",
    success: "var(--ar-success)",
    warning: "var(--ar-warning)",
    danger: "var(--ar-danger)",
    ink: "var(--ar-ink)",
    ink2: "var(--ar-ink-2)",
  },
  radius: {
    sm: "var(--ar-radius-sm)",
    md: "var(--ar-radius-md)",
    lg: "var(--ar-radius-lg)",
  },
  space: {
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
  },
  shadow: {
    sm: "var(--ar-shadow-sm)",
    md: "var(--ar-shadow-md)",
  },
  z: {
    base: 0,
    sticky: 20,
    sidebar: 30,
    overlay: 40,
    modal: 50,
  },
  motion: {
    fast: "150ms",
    base: "220ms",
    ease: { duration: 0.22, ease: [0.22, 1, 0.36, 1] as [number, number, number, number] },
  },
} as const;
